# Generated by Django 3.1.2 on 2020-10-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201013_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Other', max_length=200),
            preserve_default=False,
        ),
    ]
