# Generated by Django 3.1.2 on 2020-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Wo', 'Workover'), ('Tr', 'Troubleshooting'), ('Opt', 'Optimization'), ('Other', 'Other')], max_length=200),
        ),
    ]
