# Generated by Django 3.1.2 on 2020-10-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20201013_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',)},
        ),
    ]
