# Generated by Django 3.1.3 on 2020-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201013_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='info',
            field=models.CharField(default='', max_length=500),
        ),
    ]
